// File generated by FlutterFire CLI or created for Firebase initialization
// Replace the values below with your Firebase Project credentials or run `flutterfire configure`
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRhFjAZcW8plQr93auSSd0pGJd4PVhLmw',
    appId: '1:692600916897:web:48d2d1bfbc042e9c1659e0',
    messagingSenderId: '692600916897',
    projectId: 'arillo-advmblprog',
    authDomain: 'arillo-advmblprog.firebaseapp.com',
    storageBucket: 'arillo-advmblprog.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2UXkAeMK02zt3A0tjkm7coQndu7XqpWU',
    appId: '1:692600916897:android:135d5eafe91b8f271659e0',
    messagingSenderId: '692600916897',
    projectId: 'arillo-advmblprog',
    storageBucket: 'arillo-advmblprog.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.flutterConnection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.flutterConnection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRhFjAZcW8plQr93auSSd0pGJd4PVhLmw',
    appId: '1:692600916897:web:eb56530a270b2f851659e0',
    messagingSenderId: '692600916897',
    projectId: 'arillo-advmblprog',
    authDomain: 'arillo-advmblprog.firebaseapp.com',
    storageBucket: 'arillo-advmblprog.firebasestorage.app',
  );
}
